# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr1 = np.random.random((3,3,3))
print(arr1)

[[[0.15169047 0.88818812 0.04654441]
  [0.41413906 0.9336372  0.97964221]
  [0.31707933 0.5324057  0.87465544]]

 [[0.8688147  0.30995251 0.7409804 ]
  [0.64322174 0.9174826  0.26818884]
  [0.21626055 0.7820993  0.23172598]]

 [[0.09283765 0.33834444 0.26857557]
  [0.07935334 0.56864874 0.32209625]
  [0.01183273 0.58684037 0.96485765]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
arr2 = np.diag([1, 2, 3, 4, 5])
print(arr2)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr3 = np.zeros((8, 8), dtype=int)
arr3[1::2,::2]=1
arr3[::2,1::2]=1
arr3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [4]:
arr4=np.random.random((5,5))
print(arr4)

mx=arr4.max()
mn=arr4.min()

arr4=(arr4-mn)/(mx-mn)
print("\n\nNormalized array is....")
print(arr4)

[[0.48883442 0.19274579 0.03565987 0.87406988 0.07684155]
 [0.07663398 0.36895716 0.30810042 0.09677039 0.34285899]
 [0.90020038 0.22660433 0.76532046 0.61567121 0.38520274]
 [0.0251705  0.56199661 0.12061343 0.98017795 0.35664932]
 [0.81579811 0.00282789 0.35822141 0.14076446 0.48323124]]


Normalized array is....
[[0.49726966 0.19431922 0.03359285 0.89143289 0.07572892]
 [0.07551653 0.37461426 0.31234717 0.0961196  0.34791127]
 [0.91816896 0.22896243 0.78016322 0.62704587 0.39123633]
 [0.0228604  0.57212737 0.1205152  1.         0.36202118]
 [0.83181068 0.         0.36362971 0.14113323 0.49153662]]


# 5.  How to find common values between two arrays?

In [6]:
arr5=np.array([[1,2,30],[4,50,6]])
arr6=np.array([[1,100,2],[4,400,50]])
print(arr5)
print(arr6)

print("The common values are.....\n",np.intersect1d(arr5,arr6))

[[ 1  2 30]
 [ 4 50  6]]
[[  1 100   2]
 [  4 400  50]]
The common values are.....
 [ 1  2  4 50]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday=np.datetime64('today','D')-np.timedelta64(1, 'D')
print("Yesterday date:",yesterday)

today=np.datetime64('today','D')
print("today's date:",today)

tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tommorow's date:",tomorrow)

Yesterday date: 2020-08-05
today's date: 2020-08-06
tommorow's date: 2020-08-07


# 7. Consider two random array A and B, check if they are equal

In [8]:
arr7=np.eye(5,5)
arr8=np.zeros_like(arr7)

print(arr7,"\n\n",arr8)

chck=np.allclose(arr7,arr8)
print(chck)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
n=np.random.random(10)
print(n)

n[n.argmax()]=0
print(n)

[0.21177468 0.23851635 0.93972928 0.33225428 0.9692533  0.52945471
 0.86208756 0.51351424 0.02730176 0.21680719]
[0.21177468 0.23851635 0.93972928 0.33225428 0.         0.52945471
 0.86208756 0.51351424 0.02730176 0.21680719]


# 9. How to print all the values of an array?

In [10]:
arr9=np.array([[1,2,3],[4,5,6]])
for i in arr9:
    for k in i:
        print(k)

1
2
3
4
5
6


# 10.Subtract the mean of each row of a matrix

In [11]:
y=np.random.random((4,5))
print(y)

y=y-y.mean(axis=1,keepdims=True)
print("\n\nAfter Subtracting mean...\n\n",y)

[[0.04419235 0.06151055 0.87007412 0.55825116 0.34571701]
 [0.28227523 0.65066839 0.8883126  0.61352211 0.57201101]
 [0.11266123 0.9810611  0.78389393 0.23790784 0.66904326]
 [0.57714432 0.33835582 0.97601258 0.61730328 0.26077963]]


After Subtracting mean...

 [[-0.33175669 -0.31443849  0.49412508  0.18230212 -0.03023202]
 [-0.31908264  0.04931052  0.28695474  0.01216424 -0.02934686]
 [-0.44425224  0.42414763  0.22698046 -0.31900563  0.11212978]
 [ 0.02322519 -0.2155633   0.42209345  0.06338416 -0.2931395 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
l = np.random.random((2,2))
print(l)
m=np.ones_like(l)
l+=m
print("\n\nUpdated Matrix\n\n",l)

[[0.88150691 0.69797859]
 [0.32733407 0.81054199]]


Updated Matrix

 [[1.88150691 1.69797859]
 [1.32733407 1.81054199]]


# 12.How to get the diagonal of a dot product?

In [13]:
print(arr7)
arr7.dot(np.ones_like(arr7))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 13.How to find the most frequent value in an array?

In [14]:
ap = np.random.randint(0,10,30)
print(ap)

print(np.bincount(ap).argmax())

[7 9 8 5 3 8 8 3 5 2 6 2 6 1 3 9 1 0 5 5 8 0 9 3 5 5 1 0 0 2]
5


# 14.How to get the n largest values of an array

In [15]:
ap = np.random.randint(0,10,30)
print(ap)

print(ap[np.argsort(ap)[-1:]])

[1 0 4 4 6 5 3 8 1 3 7 1 2 4 9 4 0 7 3 4 3 4 5 3 5 5 8 2 3 8]
[9]


# 15.How to create a record array from a regular array?

In [16]:
a = np.array([('Red',34.9,40),('Yellow',67.3,78)])
a

array([['Red', '34.9', '40'],
       ['Yellow', '67.3', '78']], dtype='<U6')

In [17]:
result=np.core.records.fromarrays(a.T,names='a,b')
result

rec.array([('Red', '34.9', '40'), ('Yellow', '67.3', '78')],
          dtype=[('a', '<U6'), ('b', '<U6'), ('f2', '<U6')])